# Generated by Django 4.2.7 on 2024-03-14 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 14, 5, 51, 16, 136726, tzinfo=datetime.timezone.utc)),
        ),
    ]
